window.WISHES = [
  "Hãy luôn tự hào vì con là một cá nhân duy nhất và đặc biệt theo cách của riêng mình. Cô Chi tin rằng những thế mạnh vốn có sẽ giúp con tỏa sáng rực rỡ hơn nữa trong tương lai.",
  "Mỗi lần con dũng cảm nói lên suy nghĩ của mình là một lần con đang lớn khôn. Đừng ngần ngại khám phá những điều tuyệt vời đang ẩn giấu bên trong bản thân con nhé.",
  "Cảm xúc nào cũng đáng quý và chính con là người làm chủ thế giới nội tâm kỳ diệu của mình. Hãy luôn lắng nghe và yêu thương bản thân thật nhiều trong hành trình sắp tới.",
  "Con sở hữu một trái tim ấm áp và một tư duy vô cùng nhạy bén, sáng tạo. Chỉ cần con tin vào chính mình, cô Chi tin không có thử thách nào là không thể vượt qua.",
  "Sự kiên trì và nỗ lực của con trong suốt năm học qua là món quà giá trị nhất. Hãy tiếp tục bước đi với sự tự tin và nụ cười rạng rỡ, con nhé.",
  "Đừng bao giờ so sánh chương sách của mình với người khác vì mỗi người đều có một hành trình trưởng thành riêng. Con đang làm rất tốt và hãy tiếp tục phát huy nhé",
  "Sự tử tế mà con dành cho bạn bè xung quanh giống như một vì sao ấm áp lan tỏa trong lớp học. Cảm ơn con vì đã luôn biết cách lắng nghe và chia sẻ bằng một trái tim rộng mở.",
  "Một lời chào hỏi thân thiện hay một cái ôm siết chặt từ con có thể làm thay đổi ngày mới của ai đó. Hãy luôn giữ vẹn nguyên lòng tốt và sự tinh tế này khi bước sang năm học mới nhé.",
  "Học cách thấu hiểu người khác cũng là một loại tài năng đặc biệt mà con đang sở hữu. Cô Chi hy vọng con sẽ luôn là sợi dây kết nối yêu thương ở bất cứ nơi đâu con đến.",
  "Tình bạn đẹp đẽ được xây dựng từ những điều giản dị và sự chân thành mà con đã trao đi. Giữ gìn những mối quan hệ tốt đẹp chính là cách con làm giàu thêm cho tâm hồn mình.",
  "Khi con biết cách đặt mình vào vị trí của người khác, con đã thực sự trưởng thành hơn một bậc. Hãy tiếp tục lan tỏa năng lượng tích cực này đến cộng đồng xung quanh con.",
  "Cảm ơn con vì đã luôn là một mảnh ghép hòa nhã, biết tôn trọng sự khác biệt của mọi người. Sự hiện diện của con đã làm cho tập thể lớp chúng ta trở nên trọn vẹn hơn.",
  "Trưởng thành là hành trình học cách tự chịu trách nhiệm với mỗi lựa chọn và hành động của bản thân. Cô Chi tin con đã sẵn sàng làm chủ những quyết định lớn hơn trong năm học tới.",
  "Mỗi bài học từ những lỗi sai nhỏ sẽ là viên gạch vững chắc giúp con xây dựng nên sự thông thái. Đừng sợ vấp ngã, hãy luôn nhìn nhận và sửa đổi bằng tinh thần trách nhiệm cao nhất.",
  "Việc con biết tự lập kế hoạch và quản lý thời gian chính là một sự trưởng thành. Hãy tiếp tục phát huy tính tự giác này trong cả kỳ nghỉ hè sôi động sắp tới nhé.",
  "Lời nói đi đôi với việc làm chính là cách con xây dựng niềm tin vững chắc ở mọi người xung quanh. Cô Chi rất tự hào khi thấy con ngày càng chững chạc và đáng tin cậy.",
  "Đứng trước mỗi lựa chọn khó khăn, hãy để sự trung thực và lòng tốt dẫn lối cho hành động của con. Cô Chi tin rằng con luôn biết cách đưa ra những quyết định đúng đắn nhất.",
  "Sự tự giác không cần ai nhìn thấy mới thực hiện, đó chính là vẻ đẹp thực sự của tính cách nơi con. Hãy giữ vững ngọn hải đăng trách nhiệm này để luôn đi đúng hướng.",
  "Thế giới kỹ thuật số và thực tại ngoài kia có vô vàn điều kỳ thú đang chờ bộ óc ham học hỏi của con khám phá. Hãy luôn giữ sự tò mò khoa học và tư duy nhạy bén này để tiến xa hơn.",
  "Kiến thức không chỉ nằm trong sách vở mà còn ở cách con trải nghiệm và cảm nhận cuộc sống mỗi ngày. Chúc con có một mùa hè thật ý nghĩa với những góc nhìn và khám phá mới mẻ.",
  "Khi gặp một bài toán khó hay một thử thách lớn, hãy tự nhủ rằng “mình chưa làm được” chứ không phải “không thể”. Tư duy tiến bộ sẽ luôn mở ra cho con những cánh cửa bất ngờ.",
  "Sự sáng tạo của con là một kho báu vô giá cần được khai phá liên tục. Đừng ngại thử nghiệm những ý tưởng mới và biến chúng thành những dự án tuyệt vời của riêng con.",
  "Học tập là một cuộc marathon dài hạn chứ không phải là một cuộc đua chạy nước rút. Cứ kiên trì tích lũy từng chút một, con sẽ ngỡ ngàng với phiên bản xuất sắc của mình sau này.",
  "Hãy nhìn thế giới bằng đôi mắt quan sát tinh tế và một tâm trí sẵn sàng đón nhận điều mới. Mỗi ngày qua đi đều là một cơ hội tuyệt vời để con nâng cấp bản thân mình.",
  "Đôi khi mọi chuyện không diễn ra như ý muốn, nhưng cách con mỉm cười đón nhận mới là điều quan trọng. Cô Chi tin vào sức mạnh nội tâm mạnh mẽ và kiên cường bên trong con.",
  "Sau mỗi cơn mưa trời lại sáng và sau mỗi thử thách, con lại tích lũy thêm được nhiều trải nghiệm quý giá. Hãy luôn giữ vững sự lạc quan và lòng dũng cảm khi đối diện với điều mới mẻ.",
  "Nếu cảm thấy mệt mỏi, con hoàn toàn có thể dừng lại để nghỉ ngơi và nạp lại năng lượng cho bản thân. Hãy nhớ rằng phòng tâm lý luôn là nơi an toàn sẵn sàng lắng nghe con.",
  "Dũng cảm không phải là không biết sợ, mà là dù sợ hãi nhưng con vẫn tiến về phía trước. Cô Chi tin rằng con đã làm rất tốt khi con có sự cố gắng."
];
